management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    java:
      enabled: true
