/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import com.examples.externalmodels.api.v1.controllers.FooController
import com.examples.externalmodels.api.v1.models.Wrapper

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    var wrapper: Wrapper? = null

    var controller: FooController? = null
}

fun main() {
    println(App().greeting)
}
