name: Publish Snapshots to Nexus
on:
  push:
    branches: [main]
    tags:
      - v**
  pull_request:

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{env.base-directory}}
      - name: Publish snapshot package
        run: |
          ./gradlew printVersion assemble publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_MAVEN_USER }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_MAVEN_TOKEN }}
          REF_NAME: ${{ github.head_ref || github.ref_name }}
          REF_TYPE: ${{ github.ref_type }}
